version: "3.9"

services:
  test:
    build:
      context: .
      args:
        - GITHUB_LOGIN=${GITHUB_LOGIN:?}
        - GITHUB_TOKEN=${GITHUB_TOKEN:?}
    volumes:
      - type: bind
        source: ./tests/.cache/anytype
        target: /var/anytype
      - type: bind
        source: ./tests/.cache/anytype_old
        target: /var/anytype_old
    ports:
      - "${ANYTYPE_TEST_GRPC_PORT:?}:31007"
      - "31008:31008"
