// @generated by protobuf-ts 2.9.4 with parameter client_grpc1,optimize_code_size
// @generated from protobuf file "pb/protos/snapshot.proto" (package "anytype", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { Change_Snapshot } from "./changes";
import { SmartBlockType } from "../../pkg/lib/pb/model/protos/models";
/**
 * @generated from protobuf message anytype.SnapshotWithType
 */
export interface SnapshotWithType {
    /**
     * @generated from protobuf field: anytype.model.SmartBlockType sbType = 1;
     */
    sbType: SmartBlockType;
    /**
     * @generated from protobuf field: anytype.Change.Snapshot snapshot = 2;
     */
    snapshot?: Change_Snapshot;
}
/**
 * @generated from protobuf message anytype.Profile
 */
export interface Profile {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
    /**
     * @generated from protobuf field: string avatar = 2;
     */
    avatar: string;
    /**
     * @generated from protobuf field: string address = 4;
     */
    address: string;
    /**
     * @generated from protobuf field: string spaceDashboardId = 5;
     */
    spaceDashboardId: string;
    /**
     * @generated from protobuf field: string profileId = 6;
     */
    profileId: string;
    /**
     * @generated from protobuf field: string analyticsId = 7;
     */
    analyticsId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SnapshotWithType$Type extends MessageType<SnapshotWithType> {
    constructor() {
        super("anytype.SnapshotWithType", [
            { no: 1, name: "sbType", kind: "enum", T: () => ["anytype.model.SmartBlockType", SmartBlockType] },
            { no: 2, name: "snapshot", kind: "message", T: () => Change_Snapshot }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message anytype.SnapshotWithType
 */
export const SnapshotWithType = new SnapshotWithType$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Profile$Type extends MessageType<Profile> {
    constructor() {
        super("anytype.Profile", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "avatar", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "address", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "spaceDashboardId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "profileId", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "analyticsId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message anytype.Profile
 */
export const Profile = new Profile$Type();
