name: Run Compatibility Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Tests on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Create config.yml file from secret
        env:
          CONFIG_YML_CONTENT: ${{ secrets.CONFIG_YML_CONTENT }}
        run: |
          echo "$CONFIG_YML_CONTENT" > config.yml

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm # Cache the npm modules
          key: ubuntu-latest-npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ubuntu-latest-npm-cache-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' # or specify any version you need

      - name: Cache downloaded versions
        uses: actions/cache@v3
        with:
          path: heartsFolder/ # Cache the heartsFolder directory
          key: ubuntu-latest-hearts-cache
          
      - name: Run getHearts.sh script
        run: |
          chmod +x ./getHearts.sh
          ./getHearts.sh ubuntu-latest amd64
          
      - name: Install dependencies
        run: npm install


      - name: Run compatibility tests
        run: npm run test:comp
