name: Create iOS 18.1 Simulators

on:
  workflow_dispatch:

jobs:
  create-simulators:
    runs-on: macos-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set Xcode version to one that has iOS 18.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Adjust if your environment uses a different stable/beta version
          xcode-version: '16.1'

      - name: Print Xcode version
        run: xcodebuild -version

      - name: List available iOS runtimes and device types
        run: |
          echo "===== Available Runtimes ====="
          xcrun simctl list runtimes
          echo "===== Available Device Types ====="
          xcrun simctl list devicetypes

      - name: Create and boot iOS 18.1 simulators
        run: |
          # Make sure the device-type IDs match what's actually listed in your environment
          IPHONE_15_UDID=$(xcrun simctl create "My iPhone 15" "com.apple.CoreSimulator.SimDeviceType.iPhone-15" "com.apple.CoreSimulator.SimRuntime.iOS-18-1")
          IPHONE_15_PRO_UDID=$(xcrun simctl create "My iPhone 15 Pro" "com.apple.CoreSimulator.SimDeviceType.iPhone-15-Pro" "com.apple.CoreSimulator.SimRuntime.iOS-18-1")

          echo "iPhone 15 UDID: $IPHONE_15_UDID"
          echo "iPhone 15 Pro UDID: $IPHONE_15_PRO_UDID"

          xcrun simctl boot "$IPHONE_15_UDID"
          xcrun simctl boot "$IPHONE_15_PRO_UDID"

          echo "Simulators started successfully."
